In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)


# 실행 속도 비교


In [ ]:
import random
import time

# 1. 100만 개 난수 생성
start = time.time()

random.seed(0)  # 재현성을 위해 시드 설정
arr = [random.randint(1, 100) for _ in range(1_000_000)]

# 2. 각 값을 * 2
# 람다 for 구문으로 직접 계산 
result = [x * 2 for x in arr]

end = time.time()

print(f"원본 데이터 개수: {len(arr)}")
print(f"결과 데이터 개수: {len(result)}")

# 앞부분 일부 출력
print("원본 데이터 샘플:", arr[:10])
print("변환 데이터 샘플:", result[:10])

print(f"실행 시간: {end - start:.4f} 초")

In [ ]:
import numpy as np
import time

start = time.time()

# 100만 개 난수 배열 생성
np.random.seed(0)  # 재현성을 위해 시드 설정
arr = np.random.randint(1, 100, size=1_000_000)

# 벡터 연산
# NumPy vectorized operation
result = arr * 2

end = time.time()

print("샘플:", result[:10])
print(f"실행 시간: {end - start:.6f} 초")

In [ ]:
import numpy as np

arr = np.array([1,2,3])

print(arr + 10)

In [ ]:
!pip install numpy pillow

In [ ]:
import numpy as np  # NumPy 라이브러리 import (수치 계산 및 배열 처리용)
from PIL import Image           # 이미지 저장을 위한 PIL 라이브러리

# 0~255 사이의 랜덤 정수로 구성된 224x224 크기의 RGB 이미지 생성
image = np.random.randint(
    0,      # 최소값 (포함)
    255,    # 최대값 (미포함 → 실제로는 0~254)
    (224,224,3),  # 이미지 shape: 224x224 픽셀, 3채널(RGB)
    dtype=np.uint8
)

# 생성된 이미지 배열의 형태 출력 (높이, 너비, 채널)
print(image.shape)

# numpy 배열을 PIL 이미지로 변환
img = Image.fromarray(image)

# 이미지 파일로 저장 (현재 디렉토리에 random_image.png 생성)
img.save("random_image.png")

In [ ]:
import numpy as np  # NumPy 라이브러리 불러오기

# 2행 3열 형태의 2차원 ndarray 생성
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 배열의 형태(shape) 출력
# (행 개수, 열 개수) 형태로 반환됨
print(arr.shape)   # 결과: (2, 3)

# 배열의 차원 수(ndim) 출력
# 현재는 2차원 배열이므로 결과는 2
print(arr.ndim)    # 결과: 2

# 배열 전체 원소 개수(size) 출력
# 2행 × 3열 = 총 6개 원소
print(arr.size)    # 결과: 6

In [ ]:
import numpy as np

a = np.zeros((2,3))
b = np.ones((3,3))
c = np.eye(3)

print(a)
print(b)
print(c)

In [ ]:
import numpy as np

# 0부터 11까지의 정수를 생성
# 결과: [0 1 2 3 4 5 6 7 8 9 10 11]
arr = np.arange(12)

# 1차원 배열을 3행 4열 형태로 변환
# 결과:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
arr2 = arr.reshape(3, 4)

# transpose()
# 행(row)과 열(column)을 서로 바꾸는 함수
# 3x4 -> 4x3 형태로 변경됨
arr_transpose = arr2.transpose()

# astype()
# 배열의 데이터 타입(dtype)을 변경하는 함수
# int -> float 형태로 변경
arr_float = arr2.astype(float)

# 원본 배열 출력
print("=== arr2 원본 배열 ===")
print(arr2)

# transpose 결과 출력
print("\n=== transpose() 결과 ===")
print(arr_transpose)

# astype 결과 출력
print("\n=== astype(float) 결과 ===")
print(arr_float)

# 데이터 타입 확인
print("\n=== 데이터 타입 확인 ===")
print(arr2.dtype)        # 원본 타입
print(arr_float.dtype)   # 변경된 타입

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0])
# [1 2 3]

print(arr[:,0])
# [1 4 7]

print(arr[0,:])

In [ ]:
import numpy as np

# 2차원 배열 생성
arr = np.array([
    [1,2,3],
    [4,5,6]
])

# 0번째 행의 모든 원소
print(arr[:,1])

In [ ]:
import numpy as np

scores = np.array([80,90,100])

# 평균 구하기 
print(np.mean(scores))
# 표준 편차 계산
print(np.std(scores))

In [ ]:
import numpy as np

# =========================
# np.median()
# =========================

# 중앙값(Median)을 구하는 함수
# 데이터를 정렬했을 때 가운데 위치한 값을 반환
# 이상치(outlier)의 영향을 평균보다 덜 받음

arr = np.array([10, 20, 30, 40, 100])

median_value = np.median(arr)

print(median_value)  # 30.0



# =========================
# np.percentile()
# =========================

# 백분위수(Percentile)를 구하는 함수
# 데이터에서 특정 퍼센트 위치의 값을 반환
# 예:
# 25 -> 하위 25%
# 50 -> 중앙값(median)
# 75 -> 상위 75% 위치 값

arr = np.array([10, 20, 30, 40, 50])

p25 = np.percentile(arr, 25)  # 25% 위치 값
p50 = np.percentile(arr, 50)  # 중앙값
p75 = np.percentile(arr, 75)  # 75% 위치 값

print(p25)  # 20.0
print(p50)  # 30.0
print(p75)  # 40.0



# =========================
# np.unique()
# =========================

# 중복된 값을 제거하고
# 유일한(unique) 값만 반환하는 함수

arr = np.array([1, 2, 2, 3, 3, 3, 4])

unique_values = np.unique(arr)

print(unique_values)  # [1 2 3 4]



# =========================
# np.argmax()
# =========================

# 가장 큰 값(max)의 인덱스(index)를 반환
# 실제 값이 아니라 위치를 반환함

arr = np.array([5, 10, 99, 30])

max_index = np.argmax(arr)

print(max_index)  # 2
print(arr[max_index])  # 99



# =========================
# np.argmin()
# =========================

# 가장 작은 값(min)의 인덱스(index)를 반환
# 실제 값이 아니라 위치를 반환함

arr = np.array([5, 10, -3, 30])

min_index = np.argmin(arr)

print(min_index)  # 2
print(arr[min_index])  # -3

In [ ]:
import numpy as np

# ================================
# np.where()
# ================================
# 조건에 따라 값을 선택하거나 위치를 찾는 함수

# 예제 배열 생성
arr = np.array([10, 20, 30, 40, 50])

# 조건:
# 30보다 크면 1
# 그렇지 않으면 0
result = np.where(arr > 30, 1, 0)

print("원본 배열:", arr)
print("30보다 크면 1, 아니면 0:", result)

# 결과:
# [0 0 0 1 1]

# --------------------------------
# 위치(index) 찾기 예제
# --------------------------------

# 조건을 만족하는 인덱스 반환
index_result = np.where(arr >= 30)

print("30 이상인 값의 위치:", index_result)

# 실제 값 출력
print("30 이상인 값:", arr[index_result])

# ================================
# np.any()
# ================================
# 배열 안에 하나라도 True가 있으면 True 반환

# 조건 검사
condition_any = arr > 45

print("\n45보다 큰 값 존재 여부:", condition_any)

# 하나라도 True인지 확인
any_result = np.any(condition_any)

print("하나라도 True 인가?:", any_result)

# 결과:
# True



# --------------------------------
# 모든 값이 False 인 경우
# --------------------------------

condition_any2 = arr > 100

print("\n100보다 큰 값 존재 여부:", condition_any2)

any_result2 = np.any(condition_any2)

print("하나라도 True 인가?:", any_result2)

# 결과:
# False



# ================================
# np.all()
# ================================
# 배열 안의 모든 값이 True일 때만 True 반환

# 모든 값이 5보다 큰지 검사
condition_all = arr > 5

print("\n모든 값이 5보다 큰가?:", condition_all)

all_result = np.all(condition_all)

print("모두 True 인가?:", all_result)

# 결과:
# True



# --------------------------------
# 하나라도 False가 있는 경우
# --------------------------------

condition_all2 = arr > 25

print("\n모든 값이 25보다 큰가?:", condition_all2)

all_result2 = np.all(condition_all2)

print("모두 True 인가?:", all_result2)

In [ ]:
import numpy as np

# =========================================================
# 1. np.dot()
# =========================================================
# dot() 함수는 벡터 내적 또는 행렬 곱셈을 수행한다.
# 2차원 배열에서는 일반적인 행렬 곱(Matrix Multiplication)으로 동작한다.

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 행렬 곱 수행
dot_result = np.dot(A, B)

print("=== np.dot() 결과 ===")
print(dot_result)

# 계산 과정
# [ [1*5 + 2*7, 1*6 + 2*8],
#   [3*5 + 4*7, 3*6 + 4*8] ]
#
# 결과:
# [[19 22]
#  [43 50]]



# =========================================================
# 2. np.matmul()
# =========================================================
# matmul() 함수도 행렬 곱셈을 수행한다.
# Python의 @ 연산자와 동일한 기능이다.

matmul_result = np.matmul(A, B)

print("\n=== np.matmul() 결과 ===")
print(matmul_result)

# np.dot()과 동일한 결과가 출력된다.
#
# 결과:
# [[19 22]
#  [43 50]]



# =========================================================
# 3. np.linalg.inv()
# =========================================================
# inv() 함수는 역행렬(Inverse Matrix)을 구한다.
#
# 역행렬은 다음 조건을 만족한다.
# A × A^-1 = I (단위행렬)

C = np.array([
    [1, 2],
    [3, 4]
])

# 역행렬 계산
inverse_C = np.linalg.inv(C)

print("\n=== np.linalg.inv() 결과 ===")
print(inverse_C)

# 결과 예시:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 역행렬 검증
# 원본 행렬 × 역행렬 = 단위행렬(I)
identity = np.matmul(C, inverse_C)

print("\n=== 역행렬 검증 ===")
print(identity)

# 결과:
# [[1. 0.]
#  [0. 1.]]



# =========================================================
# 4. np.linalg.det()
# =========================================================
# det() 함수는 행렬식(Determinant)을 계산한다.
#
# 행렬식이 0이면 역행렬이 존재하지 않는다.

det_C = np.linalg.det(C)

print("\n=== np.linalg.det() 결과 ===")
print(det_C)

# 계산:
# (1*4) - (2*3)
# = 4 - 6
# = -2

# 결과:
# -2.0000000000000004



# =========================================================
# 5. np.linalg.eig()
# =========================================================
# eig() 함수는 고유값(Eigenvalue)과
# 고유벡터(Eigenvector)를 계산한다.
#
# 선형대수, 머신러닝, PCA 등에 매우 중요하게 사용된다.

D = np.array([
    [4, 2],
    [1, 3]
])

# 고유값과 고유벡터 계산
eigen_values, eigen_vectors = np.linalg.eig(D)

print("\n=== np.linalg.eig() 결과 ===")

print("\n고유값(Eigenvalues)")
print(eigen_values)

print("\n고유벡터(Eigenvectors)")
print(eigen_vectors)

# 의미:
# D × v = λ × v
#
# λ (lambda) : 고유값
# v           : 고유벡터

# =========================================================
# 추가: @ 연산자
# =========================================================
# Python에서는 @ 연산자를 이용해
# 행렬 곱을 더 직관적으로 수행할 수 있다.

result_operator = A @ B

print("\n=== @ 연산자 결과 ===")
print(result_operator)

# 결과:
# [[19 22]
#  [43 50]]

In [ ]:
import numpy as np

# =========================================================
# 1. np.random.rand()
# =========================================================
# 0 ~ 1 사이의 균등분포(Uniform Distribution) 난수를 생성
# shape(행, 열)을 지정 가능

print("1. np.random.rand()")
arr_rand = np.random.rand(3, 4)   # 3행 4열 배열 생성
print(arr_rand)
print()


# =========================================================
# 2. np.random.randn()
# =========================================================
# 평균 0, 표준편차 1인 정규분포(Normal Distribution) 난수 생성
# 음수와 양수가 모두 나올 수 있음

print("2. np.random.randn()")
arr_randn = np.random.randn(3, 4)  # 3행 4열 배열 생성
print(arr_randn)
print()


# =========================================================
# 3. np.random.randint()
# =========================================================
# 지정한 범위의 랜덤 정수 생성
# randint(시작값, 종료값, 개수)
# 종료값은 포함되지 않음

print("3. np.random.randint()")
arr_int = np.random.randint(1, 100, 10)  # 1 ~ 99 사이 정수 10개 생성
print(arr_int)
print()


# =========================================================
# 4. np.random.seed()
# =========================================================
# 난수 생성 기준(seed)을 고정
# 항상 동일한 난수가 생성됨
# 실험 재현(Reproducibility)에 매우 중요

print("4. np.random.seed()")

np.random.seed(100)   # 시드값 고정

a = np.random.rand(5)
print("첫 번째 실행 결과:")
print(a)

# 다시 같은 seed 설정
np.random.seed(100)

b = np.random.rand(5)
print("두 번째 실행 결과:")
print(b)

# 결과 비교
print("두 결과가 같은가?")
print(np.array_equal(a, b))
print()


# =========================================================
# 5. np.random.shuffle()
# =========================================================
# 배열의 요소 순서를 랜덤하게 섞음
# 원본 배열 자체가 변경됨 (in-place)

print("5. np.random.shuffle()")

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("섞기 전:")
print(data)

np.random.shuffle(data)

print("섞은 후:")
print(data)
print()


# =========================================================
# 추가 예제 : shuffle과 permutation 차이
# =========================================================
# shuffle()     -> 원본 변경
# permutation() -> 원본 유지 후 새로운 배열 반환

print("추가 예제 : permutation")

data2 = np.array([10, 20, 30, 40, 50])

print("원본 배열:")
print(data2)

new_data = np.random.permutation(data2)

print("permutation 결과:")
print(new_data)

print("원본 유지 여부:")
print(data2)

In [ ]:
import numpy as np  # NumPy 라이브러리를 np라는 이름으로 불러옴 (수치 계산용)

# 1차원 배열 생성
data = np.array([10, 20, 30, 40, 50])  # 데이터 배열 생성

# 평균 계산
mean = np.mean(data)  # data의 평균값 계산

# 표준편차 계산
std = np.std(data)  # data의 표준편차 계산 (데이터가 평균에서 얼마나 퍼져있는지)

# 정규화 (Standardization)
normalized = (data - mean) / std  
# 각 데이터에서 평균을 빼고, 표준편차로 나눔
# → 평균 0, 표준편차 1인 형태로 변환 (Z-score normalization)

# 결과 출력
print(normalized)  # 정규화된 값 출력

In [1]:
import numpy as np

# =========================================================
# 1. np.random.rand()
# =========================================================
# 0 ~ 1 사이의 균등분포(Uniform Distribution) 난수를 생성
# shape(행, 열)을 지정 가능

print("1. np.random.rand()")
arr_rand = np.random.rand(3, 4)   # 3행 4열 배열 생성
print(arr_rand)
print()


# =========================================================
# 2. np.random.randn()
# =========================================================
# 평균 0, 표준편차 1인 정규분포(Normal Distribution) 난수 생성
# 음수와 양수가 모두 나올 수 있음

print("2. np.random.randn()")
arr_randn = np.random.randn(3, 4)  # 3행 4열 배열 생성
print(arr_randn)
print()


# =========================================================
# 3. np.random.randint()
# =========================================================
# 지정한 범위의 랜덤 정수 생성
# randint(시작값, 종료값, 개수)
# 종료값은 포함되지 않음

print("3. np.random.randint()")
arr_int = np.random.randint(1, 100, 10)  # 1 ~ 99 사이 정수 10개 생성
print(arr_int)
print()


# =========================================================
# 4. np.random.seed()
# =========================================================
# 난수 생성 기준(seed)을 고정
# 항상 동일한 난수가 생성됨
# 실험 재현(Reproducibility)에 매우 중요

print("4. np.random.seed()")

np.random.seed(100)   # 시드값 고정

a = np.random.rand(5)
print("첫 번째 실행 결과:")
print(a)

# 다시 같은 seed 설정
np.random.seed(100)

b = np.random.rand(5)
print("두 번째 실행 결과:")
print(b)

# 결과 비교
print("두 결과가 같은가?")
print(np.array_equal(a, b))
print()


# =========================================================
# 5. np.random.shuffle()
# =========================================================
# 배열의 요소 순서를 랜덤하게 섞음
# 원본 배열 자체가 변경됨 (in-place)

print("5. np.random.shuffle()")

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("섞기 전:")
print(data)

np.random.shuffle(data)

print("섞은 후:")
print(data)
print()


# =========================================================
# 추가 예제 : shuffle과 permutation 차이
# =========================================================
# shuffle()     -> 원본 변경
# permutation() -> 원본 유지 후 새로운 배열 반환

print("추가 예제 : permutation")

data2 = np.array([10, 20, 30, 40, 50])

print("원본 배열:")
print(data2)

new_data = np.random.permutation(data2)

print("permutation 결과:")
print(new_data)

print("원본 유지 여부:")
print(data2)

1. np.random.rand()
[[0.234826   0.93603747 0.95965992 0.34300968]
 [0.25994571 0.63432557 0.01417754 0.38675755]
 [0.83790155 0.72280631 0.16841913 0.23256587]]

2. np.random.randn()
[[-0.12121676 -0.63662588 -0.14291929  0.06843215]
 [-0.37801713 -1.50604603 -0.61680595 -1.17450338]
 [-0.17510373  2.03890261 -0.78072235 -1.28263799]]

3. np.random.randint()
[54 69 33 42 50 72 67 55 68 14]

4. np.random.seed()
첫 번째 실행 결과:
[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
두 번째 실행 결과:
[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
두 결과가 같은가?
True

5. np.random.shuffle()
섞기 전:
[1 2 3 4 5 6 7 8 9]
섞은 후:
[4 5 1 2 8 7 9 6 3]

추가 예제 : permutation
원본 배열:
[10 20 30 40 50]
permutation 결과:
[20 30 10 40 50]
원본 유지 여부:
[10 20 30 40 50]
